site_name: "Mundo Mejor Uk: LOGOS"


strict: false
watch:
  - docs
  - mkdocs.yml
site_url: https://elprofesoverdad.github.io/logos/  
repo_url: https://github.com/elprofesoverdad/logos/
use_directory_urls: true
dev_addr: "127.0.0.1:8000"
validation:  # Configuración completa para ignorar advertencias :cite[7]:cite[9]
  nav:
    omitted_files: ignore
    not_found: ignore
    absolute_links: ignore
  links:
    not_found: ignore
    anchors: ignore
    absolute_links: relative_to_docs  # Rutas absolutas desde docs_dir :cite[7]:cite[9]
    unrecognized_links: ignore



theme:
  name: material
  logo: assets/images/logo-mundo-mejor-asesores-solo-cabeza-leon.png
  favicon: assets/images/favicon1.png
  custom_dir: overrides
  language: es
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - toc.follow
    - toc.integrate

plugins:
  - search:
      lang: [es, en]
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.sincro:run_sync"


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - meta
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
      toc_depth: 6
      baselevel: 1 #
  - pymdownx.arithmatex:
      generic: true # Permite usar sintaxis genérica de LaTeX para matemáticas
  - pymdownx.betterem:
      smart_enable: all # Habilita mejor manejo de énfasis y subrayado
  - pymdownx.caret # Permite usar el símbolo ^ para superíndices
  - pymdownx.details # Permite bloques desplegables con <details>
  - pymdownx.emoji: #  Extensión para emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji # Usa Twemoji como fuente de emojis
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # Genera emojis como SVG
  - pymdownx.highlight # Resaltado de sintaxis
  - pymdownx.inlinehilite # Resaltado de sintaxis en línea
  - pymdownx.keys # Permite atajos de teclado con sintaxis como `Ctrl+S`
  - pymdownx.mark # Permite resaltar texto con el símbolo ==
  - pymdownx.smartsymbols # Permite usar símbolos inteligentes como `--` para guiones largos
  - pymdownx.tabbed:
      alternate_style: true # Permite pestañas con estilo alternativo
  - pymdownx.tasklist:
      custom_checkbox: true # Permite listas de tareas con casillas de verificación personalizadas
  - pymdownx.critic # Permite anotaciones de crítica como `++texto++` para añadir texto, `--texto--` para eliminar, etc.
  - pymdownx.tilde # Permite usar el símbolo ~ para subíndices


copyright: Copyright &copy; 2018 - 2025 Mundo Mejor Asesores Daniel Hung. +584125623825 gerente@mundomejor.uk 

extra:
  generator: false

extra_css:
  - assets/css/custom.css
 


extra_javascript:
  - assets/js/landing-page.js
  - assets/js/path-corrector.js  # Script crucial para rutas [solución práctica]
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

docs_dir: './docs'

exclude_docs: |
  .*
  /templates/
  plugins/bash/bash-ui-master/**
  programas/ejecutaPythonDesdeHtml/node_modules/**
  programas/scrcpy/scrcpy/**
  plugins/rubi/entornos/rubi-jekyll/gems/gems/**
  programas/heuristic/manuales/**
  programas/cloudflared/logos-worker/**

